### ISSUE TITLE
Contribution / collaboration request

### ISSUE THREAD

**Issue by bastianwegge** [Howard3/chia-goths#1]
Hey @Howard3 , we're working on something similar and we've made some progress along the lines of what you have done. I stumbled over go-chi a couple of days ago. We're using gofiber/supabase/htmx/hyperscript.

If you're interested in getting in contact, let me know.

We've made some progress on: Uploads/Payments integrated daisyUI and Webhooks.

In any case, good luck with this project!

**Comment by Howard3** [comment]
Hey @bastianwegge Thanks for reaching out! Contributions are welcome! Community awareness of these tools is the goal of this project and I want to help people understand not just that they exist but how to use them effectively together.

Currently I'm working on a reddit-like app as a demonstration based on the outcome of the poll here: https://twitter.com/howardl3/status/1689794692773228545

With that, I'll be introducing the concept of isolated applications in a subdirectory to continue demonstrating the stack. I'm not sure if you were thinking in terms of contribution, but if you're considering that you want to show how to integrate payments or something else, I think these would be fantastic to add to the platform as these apps within it.

**Comment by bastianwegge** [comment]
Hey @Howard3 and thanks for coming back so quickly. I'd love to contribute and I guess my co-workers will as well. I'm gonna convert our payment to go-chi about next week and send a PR.

Cheers! You can close the issue if you want.

**Comment by Howard3** [comment]
Thanks, will do! Just a preview of what
I have in mind:

https://github.com/Howard3/chia-goths/tree/dev-apps-init

You'll see here that everything is being put into internal/apps for segmentation of different potential mini apps that is being put into this codebase. It allows them to all benefit for the same initialization without being mixed together.

**Comment by bastianwegge** [comment]
@Howard3 I see separation of concerns and I really like it. Everthing here is referring to your branch: https://github.com/Howard3/chia-goths/tree/dev-apps-init 

- Don't you thing splitting up to multiple tailwind configs is a bit of a exaggeration? 
- What's the meaning of the `index.html` inside of your `assets` folders?
- Since there's no SQLite implementation yet, do you want to use something low-level like `database/sql` or higher like `gorm`?

**Comment by Howard3** [comment]
Thanks! All good points let me discuss 
- tailwind configurations in each app, I've been thinking this and want to allow for a "default". There could be legitimate reasons why a specific app may want to override tailwind but most simply won't, I agree here.
- the index.html file just keeps embed filesystem happy. If nothing is there, the program doesn't start because there's nothing to embed. It's not critical to a developed application but an under development application can trigger this error.
- I actually want to allow different applications to try different approaches so people can see different ways of achieving database interaction. For the devdit app I'm going to use dbmate to migrate files and I believe database/sql directly. It'll support Turso and local SQLite configuration.

**Comment by bastianwegge** [comment]
Happy sunday!

`index.html`:
I don't understand your term `keeps embed filesystem happy`. I deleted both `index.html` files and the server keeps starting just fine. Can you elaborate on your comment?

SQLite implementation:
What other approaches would you like to see here? I could integrate Postgres / MySQL with something like [bun](https://bun.uptrace.dev/) or [gorm](https://gorm.io/) or sqlc/sqlx but I'm not sure you actually want those in here :).

**Comment by Howard3** [comment]
Happy Sunday as well!

It's safe to delete now but if you have any directory that you're attempting to embed with zero files in it, the code will panic. 

SQL integrations I've been mostly focused on SQLite because I feel there's not sufficient attention paid to it when most apps only really need it. That said, if you have a specific integration you'd like to see, I'm all for that. If you're using Gorm for example it will easily swap backends to most sql providers.

Did you have anything specific in mind for your application?

**Comment by Howard3** [comment]
A follow-up thought here:

Because I'm hosting the demo site on fly.io and with Turso, all database interactions should be compatible with SQLite for now.

**Comment by bastianwegge** [comment]
> Did you have anything specific in mind for your application?

We're using gorm in our project, that's the reason I asked. I created a small todo-app example here: https://github.com/Howard3/chia-goths/pull/2
